query UsersPage {
  users {
    id
    name
  }
}

mutation UsersAdd($name: String!) {
  insert_users_one(object: { name: $name }) {
    id
    name
  }
}

query UserPage($userId: Int!) {
  users(where: { id: { _eq: $userId } }) {
    id
    name
  }
}

query UserPostsPage($userId: Int!) {
  users(where: { id: { _eq: $userId } }) {
    id
    name
    posts {
      id
      title
      content
    }
  }
}

query UserPostPage($userId: Int!, $postId: Int!) {
  posts(
    where: { _and: [{ userId: { _eq: $userId } }, { id: { _eq: $postId } }] }
  ) {
    id
    title
    content
  }
}

query PostsPage {
  posts {
    id
    title
    content
    user {
      id
      name
    }
  }
}

query PostPage($postId: Int!) {
  posts(where: { id: { _eq: $postId } }) {
    id
    title
    content
  }
}

query PostAddPage {
  users {
    id
    name
  }
}

mutation PostAdd($title: String!, $content: String!, $userId: Int!) {
  insert_posts_one(
    object: { title: $title, userId: $userId, content: $content }
  ) {
    id
    title
    content
  }
}
